// Code generated by protoc-gen-go.
// source: data.proto
// DO NOT EDIT!

/*
Package userdata is a generated protocol buffer package.

It is generated from these files:
	data.proto

It has these top-level messages:
	Chat
*/
package userdata

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type Chat struct {
}

func (m *Chat) Reset()         { *m = Chat{} }
func (m *Chat) String() string { return proto.CompactTextString(m) }
func (*Chat) ProtoMessage()    {}

type Chat_Request struct {
    Timestamp int64  `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
    Name      string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
    Mode      string `protobuf:"bytes,3,opt,name=mode" json:"mode,omitempty"`
    Object    string `protobuf:"bytes,4,opt,name=object" json:"object,omitempty"`
    Content   string `protobuf:"bytes,5,opt,name=content" json:"content,omitempty"`
    Passwd    string `protobuf:"bytes,6,opt,name=passwd" json:"passwd,omitempty"`
}

func (m *Chat_Request) Reset()         { *m = Chat_Request{} }
func (m *Chat_Request) String() string { return proto.CompactTextString(m) }
func (*Chat_Request) ProtoMessage()    {}

type Chat_Response struct {
    Timestamp int64  `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
    Object    string `protobuf:"bytes,2,opt,name=object" json:"object,omitempty"`
    Content   string `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
    Mode      string `protobuf:"bytes,4,opt,name=mode" json:"mode,omitempty"`
}

func (m *Chat_Response) Reset()         { *m = Chat_Response{} }
func (m *Chat_Response) String() string { return proto.CompactTextString(m) }
func (*Chat_Response) ProtoMessage()    {}
